### ISSUE TITLE
CMD Line

### ISSUE THREAD

**Issue by amcitaly** [Fillippone/NodoBitcoinforDummies#2]
Hello Filippone, I have this problem, can you help me? In CMD I can't open certutil -hashfile bitcoin-0.17.1-win64-setup.exe sha256, I think because in the meanwhile you wrote your guide the software (and the name) is updated. I have tried to change 0.17.0 (that was in your guide) with 0.17.1 but it doesn't work...

**Comment by Fillippone** [comment]
Try to copy and paste here the exact output of the CMD line you got, so I can help you more effectively. 
Of course downloaded file name and file name used in the command must be letter by letter equal.

By the way, if you speak Italian, the guide is written in Italian and I speak Italian, why are we talking in English?

**Comment by amcitaly** [comment]
Grazie Mille Filippone, si sono italiano scusa non so perchè ho scritto in inglese. Ti attacco la pagina ho provato con la tua stringa oppure a modificarla. Ti chiedo anche questo, avendo già un full node sul mio pc, ho aperto una nuova partiziona per cominciare da li. Ma secondo te ci sarebbe modo di attaccare la blockchain direttamente sull'HD esterno avendola già scaricata? Scusa tutte ste domande, ti prometto che faccio qualche tentativo ma se non sono in grado mi prendo il casa node : ) Mi rendo conto che non è semplice ora....

![cmd2](https://user-images.githubusercontent.com/46417649/50906312-1c245780-1425-11e9-96a7-027a04d16001.PNG)

**Comment by Fillippone** [comment]
Dunque,
direi che se vuoi fare certutil, il file deve essere presente nella directory. Mi pare che tu abbia scaricato un altro file, sicuramente non quello corretto, che dovrebbe essere bitcoin-0.17.1-win64-setup.exe. per questo hai l'errore, semplicemente stai provando a fare l'hash di un file che non esiste nella location del comando. 

Riguardo alla seconda domanda, come spiegato nella guida, sconsiglio. 

Fammi sapere se hai risolto!

**Comment by amcitaly** [comment]
Fatto e verificato il codice ! Grazie ho capito dove era l'inghippo, facevo il download in C però lo aprivo in F. Invece ho fatto copy+paste da C a F e funziona ora
![cattura](https://user-images.githubusercontent.com/46417649/50917286-69142800-143d-11e9-8293-86a74b972f3b.PNG)

**Comment by amcitaly** [comment]
Però penso che devo disinstallare bitcoin core dal pc. Perchè quando provo ad eseguire bitcoin qt.exe da F... mi si riapre bitcoin che ho gìà in D, cioè non la riscarica la blockchain, mi riapre il nodo e basta. Proverò questa mossa in questi giorni, mi sa che ci risentiremo : P Grazie per il supporto
